version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CMC_API_KEY=${VITE_CMC_API_KEY}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - NODE_ENV=production
    image: ghcr.io/kasino-on-kaspa/kasino-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_CMC_API_KEY=${VITE_CMC_API_KEY}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
