version: '3.8'
services:
  app:
    image: ghcr.io/kasino-on-kaspa/kaspa-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_CMC_API_KEY=${VITE_CMC_API_KEY}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_SOCKET_URL=${VITE_BACKEND_URL}
