version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VITE_CMC_API_KEY=${VITE_CMC_API_KEY}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_SOCKET_URL=http://localhost:3000
        - NODE_ENV=development
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_CMC_API_KEY=${VITE_CMC_API_KEY}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_SOCKET_URL=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
