name = "kasino-on-kaspa"
compatibility_date = "2025-04-03"
main = "src/index.tsx"
site = { bucket = "./dist" }

[build]
command = "npm run build"
cwd = "./"

[env.production]
name = "kasino-on-kaspa"
route = { pattern = "kasino.kaspa.org", zone_name = "kaspa.org" }

[env.staging]
name = "kasino-on-kaspa-staging"
route = { pattern = "staging.kasino.kaspa.org", zone_name = "kaspa.org" }

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "leaderboard"
preview_id = "leaderboard-preview"