import { Icon } from "@iconify/react/dist/iconify.js";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";

export default function ProvablyFair({
  clientSeed,
  setClientSeed,
  serverSeedHash,
  sessionId,
}: {
  clientSeed: string;
  setClientSeed: (seed: string) => void;
  serverSeedHash: string;
  sessionId: string;
}) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <div className="w-fit flex items-center gap-2 cursor-pointer">
          <Icon icon="mdi:verified" className="text-green-500" />
          <p className="text-[10px] md:text-xs font-Onest font-black text-green-500">
            PROVABLY FAIR
          </p>
        </div>
      </DialogTrigger>
      <DialogContent className="bg-[#2A2A2A] border border-white/10 text-white rounded-3xl w-[90vw] lg:w-[350px] p-2">
        <div className="space-y-4">
          <div className="bg-[#444] rounded-2xl p-2  space-y-3">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Icon
                  icon="mynaui:hash-waves-solid"
                  className="text-white/60"
                />
                <p className="text-xs text-white/60  font-Onest font-black">
                  SERVER SEED HASH
                </p>
              </div>
              <div className="bg-[#2A2A2A] rounded-xl p-2">
                <p className="text-xs text-white/80 font-mono p-2 break-all">
                  {serverSeedHash || "Not available"}
                </p>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Icon icon="solar:gamepad-bold" className="text-white/60" />
                <p className="text-xs text-white/60 font-Onest font-black">
                  SESSION ID
                </p>
              </div>
              <div className="bg-[#2A2A2A] rounded-xl p-2">
                <p className="text-xs text-white/80 font-mono break-all p-2">
                  {sessionId || "Not available"}
                </p>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Icon
                  icon="iconamoon:playlist-shuffle-bold"
                  className="text-white/60"
                />
                <p className="text-xs text-white/60 font-Onest font-black">
                  CLIENT SEED
                </p>
              </div>
              <div className="bg-[#2A2A2A] rounded-xl p-2">
                <input
                  type="text"
                  value={clientSeed}
                  onChange={(e) => setClientSeed(e.target.value)}
                  className="w-full bg-transparent text-xs text-white/80 font-mono outline-none p-2"
                  placeholder="Enter client seed"
                />
              </div>
            </div>
          </div>

          <div className="text-xs text-white/60 px-2 font-Onest pb-2">
            <p className="mb-2">How it works:</p>
            <ul className="list-disc list-inside space-y-1">
              <li>Server seed is generated before each game</li>
              <li>Client seed is generated by the player</li>
              <li>Both seeds are combined to determine the outcome</li>
              <li>Results can be verified using the seed hash</li>
            </ul>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
